'use strict';

/**
 * 10 realistic dummy jewelry products for Arte&Ingegno.
 *
 * All products:
 *  - productType: "Jewelry"
 *  - vendor: "Arte&Ingegno"
 *  - status: DRAFT (safe — won't be visible in the storefront)
 *  - base metal: ottone (brass), gold-plated
 *  - nickel_free + hypoallergenic: true (brand standard)
 *
 * Metafield namespaces match the .graphql definitions:
 *  - shared fields  → namespace: "custom_shared"
 *  - jewelry fields → namespace: "custom_jewelry"
 *
 * theme_refs and editorial_collections are omitted — no metaobject
 * instances exist yet to reference.
 */

const PRODUCTS = [
  {
    title: "Collana Ancora d'Oro",
    descriptionHtml: `<p>Un'ancora in ottone dorato che richiama le tradizioni marinare del Mediterraneo. Leggera ma dal carattere deciso, porta con sé il significato di stabilità e ritorno a casa.</p>`,
    price: '48.00',
    metafields: {
      story: "L'ancora è uno dei simboli più antichi della navigazione: protezione, speranza di ritorno, legame con il mare. Questo pezzo nasce da un disegno a mano, poi lavorato artigianalmente in ottone e rifinito con una placca in oro giallo 18k.",
      care: "Evitare il contatto con acqua, profumi e creme. Conservare in sacchetto antiossidante. Pulire con panno morbido asciutto.",
      handcrafted: "true",
      made_to_order: "false",
      lead_time_days: "3",
      packaging: "Sacchettino in velluto blu con nastro dorato",
      occasion: '["Compleanno","Regalo"]',
      sub_type: "Collana",
      base_metal: "Ottone",
      plating: "Oro giallo 18k",
      closure: "Moschettone dorato",
      chain_length_cm: "45",
      weight_grams: "8.5",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Bracciale Timone',
    descriptionHtml: `<p>Il timone in miniatura reso bracciale: simbolo di guida e direzione. Cinque raggi lavorati a mano, finitura oro giallo su ottone.</p>`,
    price: '52.00',
    metafields: {
      story: "Il timone governa la rotta — in mare come nella vita. Questo bracciale rigido porta inciso il motivo del timone a sei raggi, lavorato a stampo su ottone pieno e dorato a caldo.",
      care: "Evitare contatto con acqua e cosmetici. Riporre separatamente per evitare graffi.",
      handcrafted: "true",
      made_to_order: "false",
      lead_time_days: "3",
      packaging: "Scatolina rigida bianca con logo Arte&Ingegno",
      occasion: '["Compleanno","Anniversario","Regalo"]',
      sub_type: "Bracciale",
      base_metal: "Ottone",
      plating: "Oro giallo 18k",
      closure: "T-bar dorato",
      weight_grams: "12.0",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Orecchini Stella Marina',
    descriptionHtml: `<p>Stella marina a cinque punte, leggera e luminosa. Perfetta da portare ogni giorno, abbina il tema del mare a un'estetica contemporanea.</p>`,
    price: '38.00',
    metafields: {
      story: "La stella marina riappare nelle spiagge di tutto il Mediterraneo dopo ogni tempesta — simbolo di resilienza e bellezza ritrovata. Questi orecchini vengono stampati su ottone sottile e dorati singolarmente a mano.",
      care: "Non bagnare. Non esporre a profumi diretti. Conservare negli appositi tappi in silicone inclusi.",
      handcrafted: "true",
      made_to_order: "false",
      lead_time_days: "3",
      packaging: "Sacchettino in velluto con cartellino illustrato",
      occasion: '["Compleanno","Estate","Regalo"]',
      sub_type: "Orecchini",
      base_metal: "Ottone",
      plating: "Oro giallo 18k",
      closure: "Perno con farfallina dorata",
      weight_grams: "4.2",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Anello Nodo Marinaro',
    descriptionHtml: `<p>Il nodo marinaro più famoso — il nodo savoia — reinterpretato come anello. Robusto e geometrico, in ottone dorato massiccio.</p>`,
    price: '44.00',
    metafields: {
      story: "I marinai usavano i nodi come firma: ogni equipaggio aveva il proprio. Il nodo savoia, detto anche nodo d'amore, unisce due capi in un abbraccio inestricabile. Questo anello lo riproduce in ottone pieno con rifinitura oro giallo.",
      care: "Evitare il contatto prolungato con acqua. Non indossare durante attività fisica intensa.",
      handcrafted: "true",
      made_to_order: "true",
      lead_time_days: "7",
      packaging: "Scatolina in cartone riciclato con cordoncino marino",
      occasion: '["Anniversario","Regalo","Uso quotidiano"]',
      sub_type: "Anello",
      base_metal: "Ottone",
      plating: "Oro giallo 18k",
      weight_grams: "6.0",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Collana Conchiglia Nacar',
    descriptionHtml: `<p>Conchiglia madreperlacea montata su catena sottile in ottone oro rosa. La versione romantica della nostra collezione marina.</p>`,
    price: '55.00',
    metafields: {
      story: "Le conchiglie erano moneta, ornamento e messaggio prima ancora della scrittura. Questa conchiglia in madreperla sintetica è montata su una montatura artigianale in ottone e la catena viene saldata a mano anello per anello.",
      care: "La madreperla è sensibile agli acidi. Evitare contatto con profumi, sudore e acqua marina.",
      handcrafted: "true",
      made_to_order: "false",
      lead_time_days: "5",
      packaging: "Sacchettino in organza bianca con bigliettino scritto a mano",
      occasion: '["Compleanno","Matrimonio","Estate","Regalo"]',
      sub_type: "Collana",
      base_metal: "Ottone",
      plating: "Oro rosa 18k",
      closure: "Moschettone oro rosa",
      chain_length_cm: "42",
      weight_grams: "7.8",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Bracciale Onda Dorata',
    descriptionHtml: `<p>Bracciale a catena con elemento centrale a forma di onda stilizzata. Il ritmo del mare portato al polso.</p>`,
    price: '46.00',
    metafields: {
      story: "L'onda non si ripete mai uguale — eppure il suo movimento è sempre riconoscibile. L'elemento centrale di questo bracciale è scolpito a mano sulla cera e poi fuso in ottone con la tecnica della cera persa.",
      care: "Evitare contatto con acqua salata e cloro. Conservare in sacchettino antiossidante.",
      handcrafted: "true",
      made_to_order: "false",
      lead_time_days: "3",
      packaging: "Sacchettino in velluto blu con nastro dorato",
      occasion: '["Compleanno","Estate","Uso quotidiano"]',
      sub_type: "Bracciale",
      base_metal: "Ottone",
      plating: "Oro giallo 18k",
      closure: "Chiusura a moschettone",
      weight_grams: "9.5",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Orecchini Bussola',
    descriptionHtml: `<p>Rosa dei venti miniaturizzata su orecchino a lobo. Quattro punti cardinali, finitura oro bianco per un effetto contemporaneo.</p>`,
    price: '41.00',
    metafields: {
      story: "La bussola ha orientato i navigatori per secoli prima del GPS. Questi orecchini riprendono il simbolo della rosa dei venti in versione micro, incisa a laser su ottone e rifinita a mano con placcatura in oro bianco.",
      care: "Evitare contatto con profumi e lacche per capelli. Conservare nei tappi di protezione.",
      handcrafted: "true",
      made_to_order: "false",
      lead_time_days: "3",
      packaging: "Cartoncino presentazione con sacchettino in velluto",
      occasion: '["Compleanno","Regalo","Uso quotidiano"]',
      sub_type: "Orecchini",
      base_metal: "Ottone",
      plating: "Oro bianco 18k",
      closure: "Monachella con chiusura a vite",
      weight_grams: "5.1",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Collana Rosa dei Venti',
    descriptionHtml: `<p>Il simbolo della navigazione per eccellenza, reso collana. Pendente grande su catena lunga — pezzo statement con anima marina.</p>`,
    price: '68.00',
    metafields: {
      story: "La rosa dei venti indicava ai marinai le direzioni quando le coste erano scomparse all'orizzonte. Questo pendente di grandi dimensioni è stampato a caldo su ottone spesso, rifinito a lima e placcato con tre passate di oro giallo.",
      care: "Non bagnare. Riporre separatamente su superficie morbida. Pulire con panno in microfibra.",
      handcrafted: "true",
      made_to_order: "true",
      lead_time_days: "10",
      packaging: "Scatola regalo rigida con cuscino in seta e nastro",
      occasion: '["Compleanno","Anniversario","Natale","Regalo importante"]',
      sub_type: "Collana",
      base_metal: "Ottone",
      plating: "Oro giallo 18k",
      closure: "Granchietto dorato regolabile",
      chain_length_cm: "50",
      weight_grams: "11.2",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Anello Delfino Tuffante',
    descriptionHtml: `<p>Un delfino in picchiata avvolge il dito. Scultura in miniatura in ottone dorato, pezzo unico fatto a mano.</p>`,
    price: '49.00',
    metafields: {
      story: "Il delfino accompagnava le navi romane come buon auspicio — velocità, intelligenza, fedeltà. Questo anello nasce da un modellino in argilla, poi rifinito e fuso in ottone. Ogni esemplare è leggermente diverso dagli altri.",
      care: "Evitare urti e pressioni laterali. Non bagnare. Conservare separato dagli altri gioielli.",
      handcrafted: "true",
      made_to_order: "true",
      lead_time_days: "7",
      packaging: "Scatolina in cartone riciclato con cordoncino marino",
      occasion: '["Compleanno","Regalo","Pezzo da collezione"]',
      sub_type: "Anello",
      base_metal: "Ottone",
      plating: "Oro giallo 18k",
      weight_grams: "7.3",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
  {
    title: 'Bracciale Perla di Mare',
    descriptionHtml: `<p>Catena in ottone oro rosa con perla marina sintetica centrale. Raffinato, femminile, con il mare come ispirazione silenziosa.</p>`,
    price: '58.00',
    metafields: {
      story: "La perla si forma come difesa — un granello di sabbia trasformato in bellezza dalla pazienza della natura. La perla sintetica di questo bracciale riproduce la lucentezza naturale con un processo artigianale a più strati, montata su una catena saldata a mano.",
      care: "La perla è sensibile ai prodotti chimici. Indossare dopo aver applicato profumo e cosmetici. Conservare separata.",
      handcrafted: "true",
      made_to_order: "false",
      lead_time_days: "5",
      packaging: "Scatolina rigida bianca con logo Arte&Ingegno e nastro rosa",
      occasion: '["Compleanno","Matrimonio","Anniversario","Regalo"]',
      sub_type: "Bracciale",
      base_metal: "Ottone",
      plating: "Oro rosa 18k",
      closure: "Bottone magnetico dorato",
      weight_grams: "14.0",
      nickel_free: "true",
      hypoallergenic: "true",
    },
  },
];

module.exports = PRODUCTS;
